//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerseLang.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TerseLang.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aaa
        ///aah
        ///aal
        ///aam
        ///aas
        ///aba
        ///abb
        ///abc
        ///abd
        ///abe
        ///aby
        ///abl
        ///abn
        ///abo
        ///abp
        ///abr
        ///abs
        ///abt
        ///abu
        ///abv
        ///acc
        ///ace
        ///ach
        ///acy
        ///ack
        ///act
        ///ada
        ///adc
        ///add
        ///ade
        ///ady
        ///adj
        ///adm
        ///ado
        ///adp
        ///ads
        ///adv
        ///adz
        ///aeq
        ///aer
        ///aes
        ///aet
        ///afb
        ///afd
        ///aff
        ///aft
        ///aga
        ///age
        ///agy
        ///ago
        ///agr
        ///agt
        ///aha
        ///ahi
        ///aho
        ///ahs
        ///aht
        ///ahu
        ///aid
        ///aye
        ///aik
        ///ail
        ///aim
        ///ain
        ///air
        ///ais
        ///ays
        ///ait
        ///ayu
        ///aix
        ///aka
        ///ake
        ///ako
        ///aku
        ///ala
        ///alb
        ///alc
        ///ald
        ///ale
        ///alf
        ///alg
        ///aly
        ///alk
        ///all
        ///aln
        ///alo
        ///alp
        ///als
        ///alt
        ///alw
        ///ama
        ///amb
        ///ame
        ///ami
        ///amy
        ///amp
        ///amt
        ///amu
        ///ana
        ///anc
        ///and
        ///ane
        ///an [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DICTIONARY {
            get {
                return ResourceManager.GetString("DICTIONARY", resourceCulture);
            }
        }
    }
}
